spring:
  cloud:
    gateway:
      discovery:
        locator:
          #开启以服务id去注册中心上获取转发地址
          enabled: true
          ##小写serviceId
          lower-case-service-id: true
      routes:
        - id: product-client
          uri: lb://product-client
          filters:
            - StripPrefix=1
          predicates:
            - Path=/product/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service.stockmgr.svc.cluster.local:8888/eureka
    instance:
      prefer-ip-address: true   #使用ip地址向eureka server进行注册
      instance-id: ${spring.cloud.client.ip-address}:${server.port}   #设置eureka控制台中显示的注册信息
      lease-renewal-interval-in-seconds: 5         #续约间隔时间
      lease-expiration-duration-in-seconds: 15     #续约到期时间