spring:
  datasource:
    url: jdbc:mysql://mysql.default:3306/tb_product?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  instance:
    prefer-ip-address: true #如果为false可能出错找不到服务的错误
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service.stockmgr.svc.cluster.local:8888/eureka
    instance:
      prefer-ip-address: true   #使用ip地址向eureka server进行注册
      instance-id: ${spring.cloud.client.ip-address}:${server.port}   #设置eureka控制台中显示的注册信息
      lease-renewal-interval-in-seconds: 5         #续约间隔时间
      lease-expiration-duration-in-seconds: 15     #续约到期时间